
CREATE TABLE user_authentication (
  `user` VARCHAR(255) NOT NULL,
  `token` CHAR(36) NOT NULL,
  `expiry` TIMESTAMP NOT NULL,
  `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (token),
  FOREIGN KEY (user) REFERENCES user(email)
);

ALTER TABLE user DROP COLUMN `key`;
